### ISSUE TITLE
Unable to parse/process resolve-hits input data file "Pfam-A_notc_18.out" of format hmmsearch_out. Error was: Failed to parse a number (of type j) from CS

### ISSUE THREAD

**Issue by bordin89** [UCL/cathpy#13]
Hello CATH! This error is thrown when I used cath-resolve-hits on the full output of hmmsearch against Pfam-A.

This is the command I ran 

`cath-resolve-hits.macos --min-dc-hmm-coverage=80 --worst-permissible-bitscore 25 --output-hmmer-aln --input-format  hmmsearch_out fulloutput/Pfam-A_notc_18.out > crh/Pfam-A_notc_1e18.crh`

The hmmsearch output is complete and the run was successful. 

cath-resolve-hits output a regular crh file  if I use the domtblout instead. Could it be that one of the flags that are specific to the hmmsearch_output are not compatible with Pfam or Pfam-style names?

**Comment by sillitoe** [comment]
Thanks - could you attach the (preferably smallest) version of input file that allows me to repeat the error?

**Comment by sillitoe** [comment]
Also, which version of hmmsearch?

**Comment by bordin89** [comment]
Hi Ian, here's the link to the full output
`/cath/people2/ucbtnb4/tmp/Pfam-A_notc_18.out`
hmmsearch version 3.3

**Comment by sillitoe** [comment]
Thanks - looks like this has been fixed in the latest version of `cath-resolve-hits` - will upgrade the binaries included in this package

**Comment by sillitoe** [comment]
Fixed in #16 and released to pypi as v0.4.0

**Comment by sillitoe** [comment]
Could you check and close the issue if you're happy it has been fixed.

**Comment by bordin89** [comment]
Just tested the new version, it works perfectly. Thanks a lot!
