### ISSUE TITLE
Installation process error while using cath-align-scorecons

### ISSUE THREAD

**Issue by bordin89** [UCL/cathpy#4]
It seems that scorecons isn't installed properly. 

cathpy.error.ParseError: Failed to find DOPS score in scorecons output:  (STDERR: Reading FASTA file....
Finishing parsing....
Could not find a non-empty matrix file in list: "/cath/homes2/ucbtnb4/data/3.40.50.620_gardener_benchmark/venv/lib/python3.7/site-packages/cathpy/tools/data/PET91mod.mat2

**Comment by sillitoe** [comment]
Thanks - this was fixed in HEAD, needed to bump the release on PyPI.

Would be handy to get a build working from "latest release" as well as HEAD...
